-- Screentime schema.
--
-- Conventions that matter and must not be changed casually:
--   * every instant is timestamptz, stored in UTC. The calendar day and the
--     week are derived in Europe/Zurich by the application, never by SQL
--     hour arithmetic.
--   * week_start is the Monday of a week, as a plain date in local time.
--   * balances are computed on read from sessions and adjustments. There is
--     no running total column anywhere, on purpose.

create table users (
    id            bigint generated by default as identity primary key,
    username      varchar(64)  not null,
    password_hash varchar(100) not null,
    display_name  varchar(64)  not null,
    role          varchar(16)  not null,
    active        boolean      not null default true,
    created_at    timestamptz  not null default now(),
    constraint uq_users_username unique (username),
    constraint ck_users_role check (role in ('CHILD', 'PARENT'))
);

create table devices (
    id         bigint generated by default as identity primary key,
    name       varchar(64) not null,
    active     boolean     not null default true,
    sort_order integer     not null default 0,
    constraint uq_devices_name unique (name)
);

create table settings (
    key        varchar(64)  primary key,
    value      varchar(256) not null,
    updated_at timestamptz  not null default now(),
    updated_by bigint       references users (id)
);

create table sessions (
    id          bigint generated by default as identity primary key,
    user_id     bigint      not null references users (id),
    started_at  timestamptz not null,
    ended_at    timestamptz,
    minutes     integer,
    device_id   bigint      not null references devices (id),
    type        varchar(8)  not null,
    source      varchar(8)  not null,
    created_by  bigint      not null references users (id),
    auto_closed boolean     not null default false,
    note        varchar(512),
    constraint ck_sessions_type check (type in ('FUN', 'QUICK', 'FILM')),
    constraint ck_sessions_source check (source in ('TIMER', 'MANUAL')),
    constraint ck_sessions_minutes_positive check (minutes is null or minutes >= 0),
    constraint ck_sessions_order check (ended_at is null or ended_at >= started_at),
    -- a closed session always carries its minutes, an open one never does
    constraint ck_sessions_closed check (
        (ended_at is null and minutes is null) or
        (ended_at is not null and minutes is not null)
    ),
    -- a manual entry is booked complete, it is never left open
    constraint ck_sessions_manual_closed check (source <> 'MANUAL' or ended_at is not null)
);

-- one open session per user, enforced by the database and not only by code
create unique index uq_sessions_one_open_per_user
    on sessions (user_id) where ended_at is null;

create index ix_sessions_started_at on sessions (started_at);
create index ix_sessions_user_started on sessions (user_id, started_at);

create table week_flags (
    week_start   date    primary key,
    holiday      boolean not null default false,
    bonus_active boolean not null default false
);

create table weekly_checks (
    id               bigint generated by default as identity primary key,
    week_start       date        not null,
    logged_minutes   integer     not null,
    reported_minutes integer     not null,
    difference       integer     not null,
    penalty_minutes  integer     not null,
    clean            boolean     not null,
    deliberate       boolean     not null default false,
    checked_by       bigint      not null references users (id),
    checked_at       timestamptz not null default now(),
    constraint uq_weekly_checks_week unique (week_start),
    constraint ck_weekly_checks_penalty check (penalty_minutes >= 0)
);

-- what each device reported for that week. Kept so a saved check can be
-- shown again device by device, which is the whole point of the review.
create table weekly_check_devices (
    check_id  bigint  not null references weekly_checks (id) on delete cascade,
    device_id bigint  not null references devices (id),
    minutes   integer not null,
    primary key (check_id, device_id),
    constraint ck_weekly_check_devices_minutes check (minutes >= 0)
);

create table adjustments (
    id         bigint generated by default as identity primary key,
    week_start date        not null,
    minutes    integer     not null,
    reason     varchar(256) not null,
    -- set when the weekly check wrote this row. A replacement check reverses
    -- its predecessor through this link, so penalties never stack.
    check_id   bigint      references weekly_checks (id) on delete cascade,
    created_by bigint      not null references users (id),
    created_at timestamptz not null default now()
);

create index ix_adjustments_week on adjustments (week_start);
create index ix_adjustments_check on adjustments (check_id);

create table audit_log (
    id        bigint generated by default as identity primary key,
    entity    varchar(32) not null,
    entity_id bigint,
    action    varchar(16) not null,
    old_value text,
    new_value text,
    user_id   bigint      references users (id),
    at        timestamptz not null default now(),
    constraint ck_audit_log_action check (action in ('CREATE', 'UPDATE', 'DELETE'))
);

create index ix_audit_log_entity on audit_log (entity, entity_id);
create index ix_audit_log_at on audit_log (at);
