-- Holiday periods instead of a holiday flag per week, and settings that are
-- versioned instead of overwritten.
--
-- Every setting now exists twice, once for term time and once for the
-- holidays. Which set applies to a week is decided by how many of its days
-- fall in a holiday period (see SettingsResolver). A change to a setting is a
-- new row with the Monday it starts on, so a change made today can never alter
-- a week that is already over.

-- --------------------------------------------------------------- holidays

create table holiday_periods (
    id         bigint generated by default as identity primary key,
    name       varchar(64) not null,
    -- both ends inclusive
    start_date date        not null,
    end_date   date        not null,
    -- null only for periods carried over from the old holiday flag below
    created_by bigint      references users (id),
    created_at timestamptz not null default now(),
    constraint ck_holiday_periods_order check (end_date >= start_date),
    constraint ck_holiday_periods_name check (length(trim(name)) > 0),
    -- no day may belong to two periods. The application checks first so it
    -- can name the period in the way; this is the guarantee.
    constraint ex_holiday_periods_overlap
        exclude using gist (daterange(start_date, end_date, '[]') with &&)
);

-- A week flagged as a holiday week becomes a period of that week. Seven of
-- seven days, so the holiday set applies to it, which is what the flag meant.
insert into holiday_periods (name, start_date, end_date)
select 'Holiday week', week_start, week_start + 6
from week_flags
where holiday;

alter table week_flags drop column holiday;

-- --------------------------------------------------------------- settings

alter table settings rename to settings_v1;

create table settings (
    id         bigint generated by default as identity primary key,
    scope      varchar(8)   not null,
    key        varchar(64)  not null,
    value      varchar(256) not null,
    -- the Monday from which this value is in force
    valid_from date         not null,
    -- null for the values seeded here
    created_by bigint       references users (id),
    created_at timestamptz  not null default now(),
    constraint ck_settings_scope check (scope in ('TERM', 'HOLIDAY', 'GLOBAL')),
    constraint ck_settings_valid_from_monday check (extract(isodow from valid_from) = 1)
);

create index ix_settings_lookup on settings (scope, key, valid_from desc, id desc);

-- A row is never changed in place: a new value is a new row. Enforced here so
-- that a quick fix in psql cannot quietly rewrite the history either.
create function settings_are_append_only() returns trigger
    language plpgsql as
$$
begin
    raise exception 'settings rows are never changed in place; insert a new row with a new valid_from';
end;
$$;

create trigger tr_settings_append_only
    before update on settings
    for each row execute function settings_are_append_only();

-- 3 January 2000, a Monday: in force for every week the app can show.
-- The term values are the ones the family has now, changed or not.
insert into settings (scope, key, value, valid_from, created_by, created_at)
select 'TERM', key, value, date '2000-01-03', updated_by, updated_at
from settings_v1;

-- The holiday values start at the documented defaults. Only the budget, the
-- ceilings and the cut off differ from term time.
insert into settings (scope, key, value, valid_from) values
    ('HOLIDAY', 'weeklyMinutes', '720', date '2000-01-03'),
    ('HOLIDAY', 'weekdayCapMinutes', '120', date '2000-01-03'),
    ('HOLIDAY', 'weekendCapMinutes', '120', date '2000-01-03'),
    ('HOLIDAY', 'quickDailyMinutes', '15', date '2000-01-03'),
    ('HOLIDAY', 'cutoffHour', '21', date '2000-01-03'),
    ('HOLIDAY', 'bonusMinutes', '60', date '2000-01-03'),
    ('HOLIDAY', 'bonusWeekendCapMinutes', '150', date '2000-01-03'),
    ('HOLIDAY', 'maxPenaltyMinutes', '120', date '2000-01-03'),
    ('HOLIDAY', 'toleranceMinutes', '10', date '2000-01-03'),
    ('HOLIDAY', 'manualMaxMinutes', '240', date '2000-01-03'),
    ('HOLIDAY', 'deliberatePenaltyMinutes', '60', date '2000-01-03'),
    -- four or more holiday days of seven make the whole week a holiday week
    ('GLOBAL', 'holidayWeekThresholdDays', '4', date '2000-01-03');

-- --------------------------------------------------------- weekly checks

-- A check keeps the budget it was computed against, so the history stays
-- readable even if somebody later edits the past.
alter table weekly_checks add column budget_minutes integer;
alter table weekly_checks add column tolerance_minutes integer;
alter table weekly_checks add column settings_scope varchar(8);

-- checks made so far were all made against the one set there was
update weekly_checks c
set budget_minutes    = (select value::integer from settings_v1 where key = 'weeklyMinutes')
                        + case when coalesce(f.bonus_active, false)
                               then (select value::integer from settings_v1 where key = 'bonusMinutes')
                               else 0 end,
    tolerance_minutes = (select value::integer from settings_v1 where key = 'toleranceMinutes'),
    settings_scope    = 'TERM'
from (select c2.id, wf.bonus_active
      from weekly_checks c2
      left join week_flags wf on wf.week_start = c2.week_start) f
where f.id = c.id;

alter table weekly_checks alter column budget_minutes set not null;
alter table weekly_checks alter column tolerance_minutes set not null;
alter table weekly_checks alter column settings_scope set not null;
alter table weekly_checks add constraint ck_weekly_checks_scope check (settings_scope in ('TERM', 'HOLIDAY'));

drop table settings_v1;
