-- Reminders the child ticks before screen time starts: "homework first",
-- "laundry". Parents add them; nothing is seeded.

create table checklist_items (
    id          bigint generated by default as identity primary key,
    text        varchar(200) not null,
    -- the days of the week it is due, as a comma separated list of
    -- java.time.DayOfWeek names; null means every day
    weekdays    varchar(64),
    -- both ends inclusive, either may be open
    valid_from  date,
    valid_until date,
    sort_order  integer      not null default 0,
    -- false once a parent removes it; the row stays so past ticks still
    -- point at something
    active      boolean      not null default true,
    created_by  bigint       not null references users (id),
    created_at  timestamptz  not null default now(),
    constraint ck_checklist_items_text check (length(trim(text)) > 0),
    constraint ck_checklist_items_range check (
        valid_from is null or valid_until is null or valid_until >= valid_from),
    constraint ck_checklist_items_weekdays check (weekdays is null or weekdays ~
        '^(MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY|SUNDAY)(,(MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY|SUNDAY))*$')
);

-- One row per item ticked for one start of screen time. The text is copied,
-- so a parent rewording an item later does not rewrite what was ticked.
create table checklist_ticks (
    id         bigint generated by default as identity primary key,
    session_id bigint       not null references sessions (id) on delete cascade,
    item_id    bigint       not null references checklist_items (id),
    item_text  varchar(200) not null,
    user_id    bigint       not null references users (id),
    ticked_at  timestamptz  not null,
    constraint uq_checklist_ticks_session_item unique (session_id, item_id)
);

create index ix_checklist_ticks_session on checklist_ticks (session_id);
